**AMB2162-PALLAVI_P_BHAT**

NUMPPY

In [ ]:
# array indexing
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])



1


In [ ]:
#slicig in 1d array
import numpy as np
arr=np.array([2,4,6,8,10])
print(arr[3:6])
print(arr[:5])

[ 8 10]
[ 2  4  6  8 10]


In [ ]:
bdhde

In [ ]:
# numpy array copy
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print( "array=",arr)
print( "x=", x)

array= [42  2  3  4  5]
x= [1 2 3 4 5]


In [ ]:
# numpy array copy
import numpy as np
arr=np.array([1,2,3,4,5])
arr1=arr
x=arr.copy()
arr[0]=42
print( "array=",arr)
print( "x=", x)
print(arr1)

array= [42  2  3  4  5]
x= [1 2 3 4 5]
[42  2  3  4  5]


In [ ]:
#reshaping
#create  a 1d array with 12 elements and convert that into 2d array 4*2

In [ ]:
#into a 3d array
#the outermost dimenstion will have 2 array
#that contains 2 arrays with 2 elements :
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newar=arr.reshape(2,3,2) #dimenstion,row,coloumn
print(newar)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
#numpy arrange function
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
#elementwise arithmetic operations
#4/02/2026
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1)
print(arr2)
print(arr1-arr2)
print(arr1+arr2)
print(arr1*arr2)
print(arr1/arr2)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[-4 -4]
 [-4 -4]]
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
concatenated_arr=np.concatenate((arr1,arr2),axis=0)
print(concatenated_arr)
# concatenate means joining together
# concatenate along rows




[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
concatenated_arr=np.concatenate((arr1,arr2),axis=1)
print(concatenated_arr)
# concatenate means joining together
# concatenate along coloumn




[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#transpose interchanging rows to columns and coloumn to row
arr=np.array([[3,4,5],[6,7,8]])
transpossed_arr=arr.transpose()
print("transposed array\n",transpossed_arr)


transposed array
 [[3 6]
 [4 7]
 [5 8]]


In [ ]:
flattend_arr=arr.flatten()
print(flattend_arr)
print(arr.shape) #gives number of rows and coloumns

[3 4 5 6 7 8]
(2, 3)


In [ ]:
import numpy as np
a =np.array([1+1j,1+0j,4.5,3,2,2j])
print("original array-->\n",a)
print("checking for complex number:\n",np.iscomplex(a))
print("checking for real number:\n",np.isreal(a))
print("checking for scale type:\n",np.isscalar(3.1))
print(np.isscalar([3.1]))

original array-->
 [1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
checking for complex number:
 [ True False False False False  True]
checking for real number:
 [False  True  True  True  True False]
checking for scale type:
 True
False


In [ ]:
arr=np.zeros((2,3)) # zeros not zero
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
one=np.ones((2,4)) # 2 rows 4 coloumns
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
one=np.ones((1,4))
one

array([[1., 1., 1., 1.]])

In [ ]:
empty=np.empty((2,3))
empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
eye=np.eye(2,)
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [ ]:
identity=np.identity(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# crop yields for 4 farms over 5 seasons (in tons )
import numpy as np
crop_yields=np.array([
   [12.5,13.2,14.1,13.8,15.2],
   [10.3,11.5,10.8,12.1,11.9],
   [15.1,14.8,16.2,15.5,16.8],
   [11.2,10.9,12.3,11.7,12.8]
 ])

print("crop yields array(tons):")
print(crop_yields)
print(f'\n shape:{crop_yields.shape}')
print(f'\n data type:{crop_yields.dtype}')
print(f'\n total number of elements:{crop_yields.size}')
print(f'\n number of dimentions:{crop_yields.ndim}')


crop yields array(tons):
[[12.5 13.2 14.1 13.8 15.2]
 [10.3 11.5 10.8 12.1 11.9]
 [15.1 14.8 16.2 15.5 16.8]
 [11.2 10.9 12.3 11.7 12.8]]

 shape:(4, 5)

 data type:float64

 total number of elements:20

 number of dimentions:2


In [ ]:
# agricultural analysis operations
total_yield =np.sum(crop_yields)
avg_yield_per_farm=np.mean(crop_yields,axis=1) #axis acts on row vise
avg_yield_per_season=np.mean(crop_yields,axis=0)
max_yield=np.max(crop_yields)
min_yield=np.min(crop_yields)

print(f'\n Total production:{total_yield}tons')
print(f'\n average per farm:{avg_yield_per_farm}tons')
print(f'\n average per season:{avg_yield_per_season}tons')
print(f'\n maximum yield :{max_yield}tons')
print(f'\n minimum yield:{min_yield}tons')


 Total production:262.7tons

 average per farm:[13.76 11.32 15.68 11.78]tons

 average per season:[12.275 12.6   13.35  13.275 14.175]tons

 maximum yield :16.8tons

 minimum yield:10.3tons


In [ ]:
#find best performing farm
best_farm=np.argmax(avg_yield_per_farm)
#np.argmax()does not return the max value itself _ it returns where that value is located
print("\n best performing farm:farm",best_farm+1)
print("their average yield ",round(avg_yield_per_farm[best_farm],2),"tons")

#or
print("\n best performing farm:farm,{best_farm+1}")
print("their average yield :{avg_yield_per_farm[best_farm]:.2},tons")
# if you take max it gives among 20 elements
# if you want to find it in farm 1 you have to give axis=1



 best performing farm:farm 3
their average yield  15.68 tons

 best performing farm:farm,{best_farm+1}
their average yield :{avg_yield_per_farm[best_farm]:.2},tons


In [ ]:
# boolean indexing finding exceptional yields
exceptional=crop_yields>15
print(exceptional)
print('\n exceptional yields (>15):')
print(crop_yields[exceptional])

[[False False False False  True]
 [False False False False False]
 [ True False  True  True  True]
 [False False False False False]]

 exceptional yields (>15):
[15.2 15.1 16.2 15.5 16.8]


In [ ]:
# conditional operations classify yields
categories=np.where(crop_yields>16,"high",
                    )